- specify branch

diff --git a/.github/workflows/copasiui-build.yml b/.github/workflows/copasiui-build.yml
--- a/.github/workflows/copasiui-build.yml
+++ b/.github/workflows/copasiui-build.yml
@@ -1,5 +1,8 @@
 name: Build CopasiUI (macOS)
 
+env:
+  copasi_branch: release/Version-4.40
+
 on:
   workflow_dispatch:
   release:
@@ -24,7 +27,7 @@ jobs:
       shell: bash
       working-directory: ${{github.workspace}}/copasi_source
       run: |
-        git checkout release/Version-4.39
+        git checkout $copasi_branch
 
     - name: Update COPASI Version
       shell: bash
@@ -50,7 +53,7 @@ jobs:
         source build-system-arm/profile/darwin-arm
         # emerge
         install-dependencies || echo "install dependencies failed"
-        release --nogit --branch release/Version-4.39 --comment stable --noscp || echo "release script failed"
+        release --nogit --branch $copasi_branch --comment stable --noscp || echo "release script failed"
 
     - name: Upload wheels
       uses: actions/upload-artifact@v3
@@ -78,7 +81,7 @@ jobs:
       shell: bash
       working-directory: ${{github.workspace}}/copasi_source
       run: |
-        git checkout release/Version-4.39
+        git checkout $copasi_branch
 
     - name: Update COPASI Version
       shell: bash
@@ -104,7 +107,7 @@ jobs:
         source build-system-intel/profile/darwin-intel
         # emerge
         install-dependencies || echo "install dependencies failed"
-        release --nogit --branch release/Version-4.39 --comment stable --noscp || echo "release script failed"
+        release --nogit --branch $copasi_branch --comment stable --noscp || echo "release script failed"
 
     - name: Upload wheels
       uses: actions/upload-artifact@v3
@@ -132,7 +135,7 @@ jobs:
       shell: bash
       working-directory: ${{github.workspace}}/copasi_source
       run: |
-        git checkout release/Version-4.39
+        git checkout $copasi_branch
 
     - name: Update COPASI Version
       shell: bash
@@ -158,7 +161,7 @@ jobs:
         source build-system/profile/linux-64
         # emerge
         install-dependencies || echo "install dependencies failed"
-        release --nogit --branch release/Version-4.39 --comment stable --noscp || echo "release script failed"
+        release --nogit --branch $copasi_branch --comment stable --noscp || echo "release script failed"
 
     - name: Upload wheels
       uses: actions/upload-artifact@v3
